export const ADD_TODO = 'TODO/ADD';
export const SET_FULFILLED_STATE = 'TODO/FULFILLED/STATE';

export const UPDATE_TODO = "TODO/UPDATE";
export const GET_TODOS_REQUEST = "TODOS/GET/REQUEST";
export const GET_TODOS_SUCCESS ="TODOS/GET/SUCCESS";

export const ADD_TODO_SUCCESS = 'TODO/ADD/SUCCESS';
export const SET_FULFILLED_SUCCESS = 'TODO/FULFILLED/SUCCESS';

